# Generated by Django 3.2.15 on 2022-09-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220906_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='first_name',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='second_name',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
