# Generated by Django 3.2.15 on 2022-09-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.CharField(choices=[('technology', 'Technology'), ('sports', 'Sports'), ('business', 'Business'), ('science', 'Science')], default='technology', max_length=50),
        ),
    ]
