# Generated by Django 3.2.15 on 2022-09-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topics',
            field=models.CharField(choices=[('technology', 'Technology'), ('sports', 'Sports'), ('business', 'Business'), ('science', 'Science'), ('other', 'Other')], default='technology', max_length=50),
        ),
    ]
