# Generated by Django 3.2.15 on 2022-09-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
        migrations.AlterField(
            model_name='post',
            name='topics',
            field=models.CharField(choices=[('technology', 'Technology'), ('sports', 'Sports'), ('business', 'Business'), ('other', 'Other')], default='technology', max_length=50),
        ),
    ]
