# Generated by Django 3.2.15 on 2022-09-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='second_name',
        ),
    ]
